// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BetterScroll: typeof import('./src/components/BetterScroll.vue')['default']
    MusicList: typeof import('./src/components/MusicList.vue')['default']
    PlayMusicBar: typeof import('./src/components/PlayMusicBar.vue')['default']
    PlayMusicDetail: typeof import('./src/components/PlayMusicDetail.vue')['default']
    PlayMusicList: typeof import('./src/components/PlayMusicList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollItem: typeof import('./src/components/ScrollItem.vue')['default']
    Title: typeof import('./src/components/Title.vue')['default']
    TopBar: typeof import('./src/components/TopBar.vue')['default']
    VanActionSheet: typeof import('vant/es')['ActionSheet']
    VanButton: typeof import('vant/es')['Button']
    VanDivider: typeof import('vant/es')['Divider']
    VanIcon: typeof import('vant/es')['Icon']
    VanPopup: typeof import('vant/es')['Popup']
    VanProgress: typeof import('vant/es')['Progress']
    VanSearch: typeof import('vant/es')['Search']
    VanSticky: typeof import('vant/es')['Sticky']
    VanSwipe: typeof import('vant/es')['Swipe']
    VanSwipeItem: typeof import('vant/es')['SwipeItem']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
    VanTag: typeof import('vant/es')['Tag']
  }
}
