<script setup>
import {ref} from 'vue'
import { getBanner } from "@/api"

const banners = ref([
  {
    "pic": "http://p1.music.126.net/-eXMYHsbLg9av1j6d0MiIg==/109951167921205999.jpg",
    "targetId": 152483839,
    "adid": null,
    "targetType": 10,
    "titleColor": "red",
    "typeTitle": "新碟首发",
    "url": null,
    "adurlV2": null,
    "exclusive": false,
    "monitorImpress": null,
    "monitorClick": null,
    "monitorType": null,
    "monitorImpressList": [],
    "monitorClickList": [],
    "monitorBlackList": null,
    "extMonitor": null,
    "extMonitorInfo": null,
    "adSource": null,
    "adLocation": null,
    "encodeId": "152483839",
    "program": null,
    "event": null,
    "video": null,
    "dynamicVideoData": null,
    "song": null,
    "bannerId": "1664533035748550",
    "alg": "banner-feature-1664533035748550",
    "scm": "1.music-homepage.homepage_banner_force.banner.5795974.541142704.null",
    "requestId": "",
    "showAdTag": true,
    "pid": null,
    "showContext": null,
    "adDispatchJson": null,
    "s_ctrp": "syspf_resourceType_10-syspf_resourceId_152483839",
    "logContext": null,
    "bannerBizType": "force_banner"
  },
  {
    "pic": "http://p1.music.126.net/zRflx9yAq2RcJRCLkhqoJg==/109951167918421874.jpg",
    "targetId": 0,
    "adid": null,
    "targetType": 3000,
    "titleColor": "blue",
    "typeTitle": "数字专辑",
    "url": "https://music.163.com/store/newalbum/detail?id=152281043",
    "adurlV2": null,
    "exclusive": false,
    "monitorImpress": null,
    "monitorClick": null,
    "monitorType": null,
    "monitorImpressList": [],
    "monitorClickList": [],
    "monitorBlackList": null,
    "extMonitor": null,
    "extMonitorInfo": null,
    "adSource": null,
    "adLocation": null,
    "encodeId": "0",
    "program": null,
    "event": null,
    "video": null,
    "dynamicVideoData": null,
    "song": null,
    "bannerId": "1664457401339175",
    "alg": "banner-feature-1664457401339175",
    "scm": "1.music-homepage.homepage_banner_force.banner.5820962.541351188.null",
    "requestId": "",
    "showAdTag": true,
    "pid": null,
    "showContext": null,
    "adDispatchJson": null,
    "s_ctrp": "syspf_resourceType_3000-syspf_resourceId_0",
    "logContext": null,
    "bannerBizType": "force_banner"
  },
  {
    "pic": "http://p1.music.126.net/Ur7hbE882MueOIDoyu3AOA==/109951167920158563.jpg",
    "targetId": 1985656714,
    "adid": null,
    "targetType": 1,
    "titleColor": "red",
    "typeTitle": "新歌首发",
    "url": null,
    "adurlV2": null,
    "exclusive": false,
    "monitorImpress": null,
    "monitorClick": null,
    "monitorType": null,
    "monitorImpressList": [],
    "monitorClickList": [],
    "monitorBlackList": null,
    "extMonitor": null,
    "extMonitorInfo": null,
    "adSource": null,
    "adLocation": null,
    "encodeId": "1985656714",
    "program": null,
    "event": null,
    "video": null,
    "dynamicVideoData": null,
    "song": {
      "name": "Heartbeat",
      "id": 1985656714,
      "pst": 0,
      "t": 0,
      "ar": [
        {
          "id": 956238,
          "name": "Shawn Mendes",
          "tns": [],
          "alias": []
        }
      ],
      "alia": [
        "电影《鳄鱼莱莱》原声"
      ],
      "pop": 5,
      "st": 0,
      "rt": "",
      "fee": 8,
      "v": 3,
      "crbt": null,
      "cf": "",
      "al": {
        "id": 152481713,
        "name": "Heartbeat (From the “Lyle, Lyle, Crocodile” Original Motion Picture Soundtrack)",
        "picUrl": "http://p4.music.126.net/Cb7xo5mwxtGPy886p1WotA==/109951167920060319.jpg",
        "tns": [],
        "pic_str": "109951167920060319",
        "pic": 109951167920060320
      },
      "dt": 140443,
      "h": {
        "br": 320000,
        "fid": 0,
        "size": 5620550,
        "vd": -44141,
        "sr": 44100
      },
      "m": {
        "br": 192000,
        "fid": 0,
        "size": 3372347,
        "vd": -41561,
        "sr": 44100
      },
      "l": {
        "br": 128000,
        "fid": 0,
        "size": 2248246,
        "vd": -40000,
        "sr": 44100
      },
      "sq": {
        "br": 949699,
        "fid": 0,
        "size": 16672415,
        "vd": -44240,
        "sr": 44100
      },
      "hr": null,
      "a": null,
      "cd": "01",
      "no": 1,
      "rtUrl": null,
      "ftype": 0,
      "rtUrls": [],
      "djId": 0,
      "copyright": 1,
      "s_id": 0,
      "mark": 270336,
      "originCoverType": 0,
      "originSongSimpleData": null,
      "tagPicList": null,
      "resourceState": true,
      "version": 3,
      "songJumpInfo": null,
      "entertainmentTags": null,
      "single": 0,
      "noCopyrightRcmd": null,
      "rtype": 0,
      "rurl": null,
      "mst": 9,
      "cp": 7003,
      "mv": 0,
      "publishTime": 1664467200000,
      "privilege": {
        "id": 1985656714,
        "fee": 8,
        "payed": 0,
        "st": 0,
        "pl": 128000,
        "dl": 0,
        "sp": 7,
        "cp": 1,
        "subp": 1,
        "cs": false,
        "maxbr": 999000,
        "fl": 128000,
        "toast": false,
        "flag": 260,
        "preSell": false,
        "playMaxbr": 999000,
        "downloadMaxbr": 999000,
        "maxBrLevel": "lossless",
        "playMaxBrLevel": "lossless",
        "downloadMaxBrLevel": "lossless",
        "plLevel": "standard",
        "dlLevel": "none",
        "flLevel": "standard",
        "rscl": null,
        "freeTrialPrivilege": {
          "resConsumable": false,
          "userConsumable": false,
          "listenType": null
        },
        "chargeInfoList": [
          {
            "rate": 128000,
            "chargeUrl": null,
            "chargeMessage": null,
            "chargeType": 0
          },
          {
            "rate": 192000,
            "chargeUrl": null,
            "chargeMessage": null,
            "chargeType": 1
          },
          {
            "rate": 320000,
            "chargeUrl": null,
            "chargeMessage": null,
            "chargeType": 1
          },
          {
            "rate": 999000,
            "chargeUrl": null,
            "chargeMessage": null,
            "chargeType": 1
          }
        ]
      },
      "alg": "banner-feature-1664458516298381"
    },
    "bannerId": "1664458516298381",
    "alg": "banner-feature-1664458516298381",
    "scm": "1.music-homepage.homepage_banner_force.banner.5825962.541140818.null",
    "requestId": "",
    "showAdTag": true,
    "pid": null,
    "showContext": null,
    "adDispatchJson": null,
    "s_ctrp": "syspf_resourceType_1-syspf_resourceId_1985656714",
    "logContext": null,
    "bannerBizType": "force_banner"
  },
  {
    "pic": "http://p1.music.126.net/Bkx5_vz2OF5EiCL6XBjlag==/109951167921210423.jpg",
    "targetId": 152291072,
    "adid": null,
    "targetType": 10,
    "titleColor": "red",
    "typeTitle": "新碟首发",
    "url": null,
    "adurlV2": null,
    "exclusive": false,
    "monitorImpress": null,
    "monitorClick": null,
    "monitorType": null,
    "monitorImpressList": [],
    "monitorClickList": [],
    "monitorBlackList": null,
    "extMonitor": null,
    "extMonitorInfo": null,
    "adSource": null,
    "adLocation": null,
    "encodeId": "152291072",
    "program": null,
    "event": null,
    "video": null,
    "dynamicVideoData": null,
    "song": null,
    "bannerId": "1664526554604119",
    "alg": "banner-feature-1664526554604119",
    "scm": "1.music-homepage.homepage_banner_force.banner.5822965.541292473.null",
    "requestId": "",
    "showAdTag": true,
    "pid": null,
    "showContext": null,
    "adDispatchJson": null,
    "s_ctrp": "syspf_resourceType_10-syspf_resourceId_152291072",
    "logContext": null,
    "bannerBizType": "force_banner"
  },
  {
    "pic": "http://p1.music.126.net/NGoHEExjL9yJCESc_lPUMQ==/109951167918519792.jpg",
    "targetId": 0,
    "adid": null,
    "targetType": 3000,
    "titleColor": "blue",
    "typeTitle": "活动",
    "url": "https://y.music.163.com/m/at/6334058243727fc9f7686b63",
    "adurlV2": null,
    "exclusive": false,
    "monitorImpress": null,
    "monitorClick": null,
    "monitorType": null,
    "monitorImpressList": [],
    "monitorClickList": [],
    "monitorBlackList": null,
    "extMonitor": null,
    "extMonitorInfo": null,
    "adSource": null,
    "adLocation": null,
    "encodeId": "0",
    "program": null,
    "event": null,
    "video": null,
    "dynamicVideoData": null,
    "song": null,
    "bannerId": "1664459277980353",
    "alg": "banner-feature-1664459277980353",
    "scm": "1.music-homepage.homepage_banner_force.banner.5812965.541170612.null",
    "requestId": "",
    "showAdTag": true,
    "pid": null,
    "showContext": null,
    "adDispatchJson": null,
    "s_ctrp": "syspf_resourceType_3000-syspf_resourceId_0",
    "logContext": null,
    "bannerBizType": "force_banner"
  },
  {
    "pic": "http://p1.music.126.net/fL47dXMfabjgdaCfsSugvQ==/109951167918553025.jpg",
    "targetId": 1984847230,
    "adid": null,
    "targetType": 1,
    "titleColor": "red",
    "typeTitle": "新歌首发",
    "url": null,
    "adurlV2": null,
    "exclusive": false,
    "monitorImpress": null,
    "monitorClick": null,
    "monitorType": null,
    "monitorImpressList": [],
    "monitorClickList": [],
    "monitorBlackList": null,
    "extMonitor": null,
    "extMonitorInfo": null,
    "adSource": null,
    "adLocation": null,
    "encodeId": "1984847230",
    "program": null,
    "event": null,
    "video": null,
    "dynamicVideoData": null,
    "song": {
      "name": "Charlie Be Quiet!",
      "id": 1984847230,
      "pst": 0,
      "t": 0,
      "ar": [
        {
          "id": 90331,
          "name": "Charlie Puth",
          "tns": [],
          "alias": []
        }
      ],
      "alia": [],
      "pop": 5,
      "st": 0,
      "rt": "",
      "fee": 8,
      "v": 3,
      "crbt": null,
      "cf": "",
      "al": {
        "id": 152297167,
        "name": "Charlie Be Quiet!",
        "picUrl": "http://p4.music.126.net/Z-gaPbMmBbvfi_Gn7e3_Yg==/109951167912776522.jpg",
        "tns": [],
        "pic_str": "109951167912776522",
        "pic": 109951167912776530
      },
      "dt": 128364,
      "h": {
        "br": 320000,
        "fid": 0,
        "size": 5136762,
        "vd": -83164,
        "sr": 44100
      },
      "m": {
        "br": 192000,
        "fid": 0,
        "size": 3082075,
        "vd": -80623,
        "sr": 44100
      },
      "l": {
        "br": 128000,
        "fid": 0,
        "size": 2054731,
        "vd": -79128,
        "sr": 44100
      },
      "sq": {
        "br": 1556984,
        "fid": 0,
        "size": 24982692,
        "vd": -83167,
        "sr": 44100
      },
      "hr": null,
      "a": null,
      "cd": "01",
      "no": 1,
      "rtUrl": null,
      "ftype": 0,
      "rtUrls": [],
      "djId": 0,
      "copyright": 1,
      "s_id": 0,
      "mark": 270336,
      "originCoverType": 0,
      "originSongSimpleData": null,
      "tagPicList": null,
      "resourceState": true,
      "version": 3,
      "songJumpInfo": null,
      "entertainmentTags": null,
      "single": 0,
      "noCopyrightRcmd": null,
      "rtype": 0,
      "rurl": null,
      "mst": 9,
      "cp": 7002,
      "mv": 0,
      "publishTime": 1664467200000,
      "privilege": {
        "id": 1984847230,
        "fee": 8,
        "payed": 0,
        "st": 0,
        "pl": 128000,
        "dl": 0,
        "sp": 7,
        "cp": 1,
        "subp": 1,
        "cs": false,
        "maxbr": 999000,
        "fl": 128000,
        "toast": false,
        "flag": 4,
        "preSell": false,
        "playMaxbr": 999000,
        "downloadMaxbr": 999000,
        "maxBrLevel": "lossless",
        "playMaxBrLevel": "lossless",
        "downloadMaxBrLevel": "lossless",
        "plLevel": "standard",
        "dlLevel": "none",
        "flLevel": "standard",
        "rscl": null,
        "freeTrialPrivilege": {
          "resConsumable": false,
          "userConsumable": false,
          "listenType": null
        },
        "chargeInfoList": [
          {
            "rate": 128000,
            "chargeUrl": null,
            "chargeMessage": null,
            "chargeType": 0
          },
          {
            "rate": 192000,
            "chargeUrl": null,
            "chargeMessage": null,
            "chargeType": 1
          },
          {
            "rate": 320000,
            "chargeUrl": null,
            "chargeMessage": null,
            "chargeType": 1
          },
          {
            "rate": 999000,
            "chargeUrl": null,
            "chargeMessage": null,
            "chargeType": 1
          }
        ]
      },
      "alg": "banner-feature-1664459711933907"
    },
    "bannerId": "1664459711933907",
    "alg": "banner-feature-1664459711933907",
    "scm": "1.music-homepage.homepage_banner_force.banner.5832962.541202354.null",
    "requestId": "",
    "showAdTag": true,
    "pid": null,
    "showContext": null,
    "adDispatchJson": null,
    "s_ctrp": "syspf_resourceType_1-syspf_resourceId_1984847230",
    "logContext": null,
    "bannerBizType": "force_banner"
  },
  {
    "pic": "http://p1.music.126.net/2p_MeeGdWzmpR06YrlleJw==/109951167921226121.jpg",
    "targetId": 1983763386,
    "adid": null,
    "targetType": 1,
    "titleColor": "red",
    "typeTitle": "热歌推荐",
    "url": null,
    "adurlV2": null,
    "exclusive": false,
    "monitorImpress": null,
    "monitorClick": null,
    "monitorType": null,
    "monitorImpressList": [],
    "monitorClickList": [],
    "monitorBlackList": null,
    "extMonitor": null,
    "extMonitorInfo": null,
    "adSource": null,
    "adLocation": null,
    "encodeId": "1983763386",
    "program": null,
    "event": null,
    "video": null,
    "dynamicVideoData": null,
    "song": {
      "name": "Mirror Mirror",
      "id": 1983763386,
      "pst": 0,
      "t": 0,
      "ar": [
        {
          "id": 30525497,
          "name": "徐艺洋",
          "tns": [],
          "alias": []
        }
      ],
      "alia": [],
      "pop": 5,
      "st": 0,
      "rt": "",
      "fee": 8,
      "v": 15,
      "crbt": null,
      "cf": "",
      "al": {
        "id": 152093782,
        "name": "Mirror Mirror",
        "picUrl": "http://p3.music.126.net/PbqV0I1-177xvK9J7Vyurw==/109951167912412825.jpg",
        "tns": [],
        "pic_str": "109951167912412825",
        "pic": 109951167912412830
      },
      "dt": 177591,
      "h": {
        "br": 320000,
        "fid": 0,
        "size": 7105965,
        "vd": -46624,
        "sr": 48000
      },
      "m": {
        "br": 192000,
        "fid": 0,
        "size": 4263597,
        "vd": -44151,
        "sr": 48000
      },
      "l": {
        "br": 128000,
        "fid": 0,
        "size": 2842413,
        "vd": -42758,
        "sr": 48000
      },
      "sq": {
        "br": 1023842,
        "fid": 0,
        "size": 22728253,
        "vd": -46462,
        "sr": 48000
      },
      "hr": {
        "br": 1791779,
        "fid": 0,
        "size": 39775661,
        "vd": -46604,
        "sr": 48000
      },
      "a": null,
      "cd": "01",
      "no": 1,
      "rtUrl": null,
      "ftype": 0,
      "rtUrls": [],
      "djId": 0,
      "copyright": 0,
      "s_id": 0,
      "mark": 536870912,
      "originCoverType": 0,
      "originSongSimpleData": null,
      "tagPicList": null,
      "resourceState": true,
      "version": 15,
      "songJumpInfo": null,
      "entertainmentTags": null,
      "single": 0,
      "noCopyrightRcmd": null,
      "rtype": 0,
      "rurl": null,
      "mst": 9,
      "cp": 2708742,
      "mv": 14566324,
      "publishTime": 1663862400000,
      "privilege": {
        "id": 1983763386,
        "fee": 8,
        "payed": 0,
        "st": 0,
        "pl": 128000,
        "dl": 0,
        "sp": 7,
        "cp": 1,
        "subp": 1,
        "cs": false,
        "maxbr": 999000,
        "fl": 128000,
        "toast": false,
        "flag": 0,
        "preSell": false,
        "playMaxbr": 999000,
        "downloadMaxbr": 999000,
        "maxBrLevel": "hires",
        "playMaxBrLevel": "hires",
        "downloadMaxBrLevel": "hires",
        "plLevel": "standard",
        "dlLevel": "none",
        "flLevel": "standard",
        "rscl": null,
        "freeTrialPrivilege": {
          "resConsumable": false,
          "userConsumable": false,
          "listenType": null
        },
        "chargeInfoList": [
          {
            "rate": 128000,
            "chargeUrl": null,
            "chargeMessage": null,
            "chargeType": 0
          },
          {
            "rate": 192000,
            "chargeUrl": null,
            "chargeMessage": null,
            "chargeType": 1
          },
          {
            "rate": 320000,
            "chargeUrl": null,
            "chargeMessage": null,
            "chargeType": 1
          },
          {
            "rate": 999000,
            "chargeUrl": null,
            "chargeMessage": null,
            "chargeType": 1
          },
          {
            "rate": 1999000,
            "chargeUrl": null,
            "chargeMessage": null,
            "chargeType": 1
          }
        ]
      },
      "alg": "banner-feature-1664533481156228"
    },
    "bannerId": "1664533481156228",
    "alg": "banner-feature-1664533481156228",
    "scm": "1.music-homepage.homepage_banner_force.banner.5841964.541235027.null",
    "requestId": "",
    "showAdTag": true,
    "pid": null,
    "showContext": null,
    "adDispatchJson": null,
    "s_ctrp": "syspf_resourceType_1-syspf_resourceId_1983763386",
    "logContext": null,
    "bannerBizType": "force_banner"
  }
])


</script>

<template>
	<!-- 轮播图 -->
  <div>
		<van-swipe :autoplay="3000" lazy-render>
			<van-swipe-item v-for="item in banners" :key="item.bannerId">
				<img :src="item.pic" />
			</van-swipe-item>
		</van-swipe>
		<van-button type="primary" />
	</div>

</template>

<style scoped>

</style>
